Repository FreeRDP/FreeRDP, pull requests merged in 2020-04, with the labels that each got.

#6021 server: fix surface command types
  server/Sample/sfreerdp.c
  server/shadow/shadow_client.c
  server/shadow/shadow_encoder.c
Labels: shadow

#6049 tls: support non-RSA keys
  libfreerdp/crypto/tls.c
Labels: backport-to-stable

#6071 Adds the title option to wlfreerdp
  client/Wayland/wlfreerdp.c
Labels: backport-to-stable

#6080 Fixi #6086: smartcard filter early abort.
  channels/smartcard/client/smartcard_operations.c
Labels: consider-for-stable

#6077 Progressive limit stack
  libfreerdp/codec/progressive.c
Labels: consider-for-stable

#6060 Fix some compiler warnings
  channels/printer/client/cups/printer_cups.c
  libfreerdp/core/nla.c
  libfreerdp/primitives/test/TestPrimitivesColors.c
  server/proxy/pf_cliprdr.c
  winpr/libwinpr/crt/test/TestUnicodeConversion.c
Labels: consider-for-stable

#6097 Refactored the parsing of the dev: command line option in the urbdrc subsystem
  channels/urbdrc/client/libusb/libusb_udevman.c
Labels: backport-to-stable

#6098 SCardReadCache/SCardWriteCache should actually cache data
  channels/smartcard/client/smartcard_operations.c
  channels/smartcard/client/smartcard_pack.c
  winpr/libwinpr/smartcard/smartcard_pcsc.c
Labels: backport-to-stable

#6095 uwac, wlfreerdp: corrected API for UwacOutput and added monitor listing
  client/Wayland/wlf_disp.c
  client/Wayland/wlf_disp.h
  client/Wayland/wlfreerdp.c
  uwac/include/uwac/uwac.h
  uwac/libuwac/uwac-display.c
  uwac/libuwac/uwac-output.c
  uwac/libuwac/uwac-priv.h
Labels: consider-for-stable, wayland

#6106 Pointer fixes
  client/common/cmdline.c
  libfreerdp/cache/pointer.c
  libfreerdp/codec/color.c
  libfreerdp/core/capabilities.c
  libfreerdp/core/update.c
Labels: consider-for-stable

#6100 Fixed #6099: Add a flag for legacy hash entries
  client/common/client.c
  include/freerdp/freerdp.h
  libfreerdp/crypto/tls.c
Labels: consider-for-stable

#6110 possible memory leak when various functions return failure.
  winpr/libwinpr/sspi/NTLM/ntlm_compute.c
Labels: consider-for-stable

#6128 libuwac/window: Fix memory leak / SIGBUS
  uwac/libuwac/uwac-priv.h
  uwac/libuwac/uwac-window.c
Labels: consider-for-stable

#6131 Workaround #6072: FFMPEG AAC encoding graded experimental
  libfreerdp/codec/dsp_ffmpeg.c
Labels: consider-for-stable

#6125 Fixed #6121: Use correct destination color format
  client/Windows/wf_graphics.c
Labels: consider-for-stable

#6129 libuwac/input: Fix memory leak
  uwac/libuwac/uwac-input.c
Labels: consider-for-stable
